spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springTotal
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


application:
  schedule:
    cron: "0 0/5 * * * ?"
  batch:
    chunkSize: 10000
  sftp:
#    host: 192.168.3.231
    host: 127.0.0.1
    port: 22
#    user: stefan
    user: magis
    privateKey: classpath:id_rsa
#    directory: /home/stefan
    directory: /home/magis

logging.level.org.apache.sshd: DEBUG